/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entidades.Producto;
import java.awt.Graphics;
import java.awt.Image;
import java.util.TreeSet;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class Principal extends javax.swing.JFrame {
  public static TreeSet<Producto> lista;

   
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        lista=new TreeSet();
    }

    public static TreeSet<Producto> getLista() {
        return lista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/Psychedelic.jpg"));
        Image miImagen = icono.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(miImagen, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miProductos = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miNombre = new javax.swing.JCheckBoxMenuItem();
        miPrecio = new javax.swing.JCheckBoxMenuItem();
        miRubro = new javax.swing.JCheckBoxMenuItem();

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TP6 De todo S.A.");

        escritorio.setPreferredSize(new java.awt.Dimension(600, 500));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 822, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        jMenu1.setText("Administracion");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        miProductos.setSelected(true);
        miProductos.setText("Gestion de Productos");
        miProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProductosActionPerformed(evt);
            }
        });
        jMenu1.add(miProductos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consutas");

        miNombre.setSelected(true);
        miNombre.setText("Consulta por Nombre");
        miNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNombreActionPerformed(evt);
            }
        });
        jMenu2.add(miNombre);

        miPrecio.setSelected(true);
        miPrecio.setText("Consulta por Precio");
        miPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrecioActionPerformed(evt);
            }
        });
        jMenu2.add(miPrecio);

        miRubro.setSelected(true);
        miRubro.setText("Consulta por Rubro");
        miRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRubroActionPerformed(evt);
            }
        });
        jMenu2.add(miRubro);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void miProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ProductoView pw=new ProductoView();
        pw.setVisible(true);
        escritorio.add(pw);
        escritorio.moveToFront(pw);
    }//GEN-LAST:event_miProductosActionPerformed

    private void miNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNombreActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ListadoNombreView pw=new ListadoNombreView();
        pw.setVisible(true);
        escritorio.add(pw);
        escritorio.moveToFront(pw);
    }//GEN-LAST:event_miNombreActionPerformed

    private void miPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrecioActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ListadoPrecioView pw=new ListadoPrecioView();
        pw.setVisible(true);
        escritorio.add(pw);
        escritorio.moveToFront(pw);
    }//GEN-LAST:event_miPrecioActionPerformed

    private void miRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRubroActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ListadoRubroView lr=new ListadoRubroView();
        lr.setVisible(true);
        escritorio.add(lr);
        escritorio.moveToFront(lr);
    }//GEN-LAST:event_miRubroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JCheckBoxMenuItem miNombre;
    private javax.swing.JCheckBoxMenuItem miPrecio;
    private javax.swing.JCheckBoxMenuItem miProductos;
    private javax.swing.JCheckBoxMenuItem miRubro;
    // End of variables declaration//GEN-END:variables
}
