/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entidades.Producto;
import entidades.ProductoData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ProductoView extends javax.swing.JInternalFrame {
ProductoData pd= new ProductoData();    
private DefaultTableModel modelo= new DefaultTableModel(){
    public boolean isCellEditable(int fila,int col){
       return false;
    }
   };    

    /**
     * Creates new form ProductoView
     */
    public ProductoView() {
        initComponents();
        armarCabecera();
        desactivarCampos();
        bGuardar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        bEliminar = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bBuevo = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tProductos = new javax.swing.JTable();
        cbCategoria = new javax.swing.JComboBox<>();
        bActualizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tPrecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sStock = new javax.swing.JSpinner();
        tDesc = new javax.swing.JTextField();
        cbRubro = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setTitle("De todo S.A.: Productos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(800, 850));
        setVerifyInputWhenFocusTarget(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gestión de Productos");

        bEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        bEliminar.setText("Eliminar");
        bEliminar.setEnabled(false);
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guarda8.png"))); // NOI18N
        bGuardar.setText("Guardar");
        bGuardar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bGuardar.setEnabled(false);
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bSalir.setText("Cerrar");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        bBuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bBuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8.png"))); // NOI18N
        bBuevo.setText("Nuevo");
        bBuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuevoActionPerformed(evt);
            }
        });

        bBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupita.png"))); // NOI18N
        bBuscar.setFocusable(false);
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Filtrar por Categoria:");

        tProductos.setOpaque(false);
        tProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tProductos);

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Limpieza", "Ropa", "Comestible", "Perfumeria", "Electronica" }));
        cbCategoria.setSelectedIndex(-1);
        cbCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCategoriaItemStateChanged(evt);
            }
        });
        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });

        bActualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/marca-doble.png"))); // NOI18N
        bActualizar.setText("Actualizar");
        bActualizar.setEnabled(false);
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Descripcion:");

        tCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tCodigoFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Rubro:");

        tPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tPrecioFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Codigo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Precio:");

        tDesc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tDescFocusLost(evt);
            }
        });

        cbRubro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Limpieza", "Ropa", "Comestible", "Perfumeria", "Electronica" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Stock:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(5, 5, 5)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sStock, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSalir)
                            .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bBuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bBuevo)
                            .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bEliminar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bBuscar)
                        .addGap(99, 99, 99)
                        .addComponent(bSalir)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bActualizar, bBuevo, bEliminar, bGuardar});

        setBounds(0, 0, 541, 588);
    }// </editor-fold>//GEN-END:initComponents

    private void bBuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
        activarCampos();
        bGuardar.setEnabled(true);
    }//GEN-LAST:event_bBuevoActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bSalirActionPerformed
    private void limpiar(){
       tCodigo.setText("");
       tDesc.setText(null);
       tPrecio.setText("");
       cbRubro.setSelectedIndex(0);//inicializa el primero
       sStock.setValue(0);
    }
    
     private void armarCabecera(){
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Categoria");
        modelo.addColumn("Stock");
        tProductos.setModel(modelo);
    }
    private void activarCampos(){
        tCodigo.setEnabled(true);
        tDesc.setEnabled(true);
        cbRubro.setEnabled(true);
        tPrecio.setEnabled(true);
        sStock.setEnabled(true);
     }
     private void desactivarCampos(){
        tCodigo.setEnabled(false);
        tDesc.setEnabled(false);
        cbRubro.setEnabled(false);
        tPrecio.setEnabled(false);
        sStock.setEnabled(false);
    }
     public void borraFilasTabla(){
       int a =modelo.getRowCount()-1;
       for(int i=a;i>=0;i--){
          modelo.removeRow(i );
       }
     }
     private void llenarTabla(){
       borraFilasTabla();
        String selectedCat =(String)cbCategoria.getSelectedItem();
        if (selectedCat!=null){
          for (Producto p:Principal.getLista()){
             if (p.getRubro().equals(selectedCat))  {

               modelo.addRow(new Object[]{p.getCodigo(),p.getDescripcion(),p.getPrecio(),p.getRubro(),p.getStock()});

            }  
          }
        }   
     }
     
     
    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        try{   
            int cod = Integer.parseInt(tCodigo.getText());
            String desc = tDesc.getText();
            double precio = Double.parseDouble(tPrecio.getText());
            String rubro = (String) cbRubro.getSelectedItem();
            int stock =(Integer)sStock.getValue();
            Producto prod = new Producto(cod,desc,precio,rubro,stock);
            pd.agregarProducto(prod);
            limpiar();
            desactivarCampos();
            bGuardar.setEnabled(false);

        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero "+e);
            limpiar();
            tCodigo.requestFocus();
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        Producto prod= new Producto();
       
        try{   
            int codBusca = Integer.parseInt(tCodigo.getText());
            prod=pd.buscarProducto(codBusca);
                if  (prod!= null){
                    tCodigo.setText(prod.getCodigo()+"");
                    tDesc.setText(prod.getDescripcion());
                    cbRubro.setSelectedItem(prod.getRubro());  
                    tPrecio.setText(prod.getPrecio()+"");
                    sStock.setValue(prod.getStock());
                    
                }else   // SI DEVOLVIO NULL
                    JOptionPane.showMessageDialog(this, "El producto no existe ");  
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "WARNING! Debe ingresar un numero ");
            limpiar();
            tCodigo.requestFocus();
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void cbCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCategoriaItemStateChanged
       
    }//GEN-LAST:event_cbCategoriaItemStateChanged

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        
        try{   
        int cod = Integer.parseInt(tCodigo.getText());
        String desc = tDesc.getText();
        double precio = Double.parseDouble(tPrecio.getText());
        String rubro = (String) cbRubro.getSelectedItem();
        int stock =(Integer)sStock.getValue();
        Producto prod = new Producto(cod,desc,precio,rubro,stock);
        pd.modificarProducto(prod);
        limpiar();
        desactivarCampos();
        llenarTabla();
         bActualizar.setEnabled(false);
        
    } catch (NumberFormatException e){
        JOptionPane.showMessageDialog(this, "Debe ingresar un numero "+e);
        limpiar();
        tCodigo.requestFocus();
       
    }
    }//GEN-LAST:event_bActualizarActionPerformed

    private void tCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCodigoFocusLost
        // TODO add your handli,ng code here:
        String formato="[0-9]*";
        
        if (!tCodigo.getText().matches(formato)){
           JOptionPane.showMessageDialog(this, "Debe ingresr Numeros");
           tCodigo.requestFocus();
        
        
        }
    }//GEN-LAST:event_tCodigoFocusLost

    private void tPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPrecioFocusLost
        // TODO add your handling code here:
        String formato="[0-9]*"+"."+"[0-9]*";
        
        if (!tCodigo.getText().matches(formato)){
           JOptionPane.showMessageDialog(this, "Debe ingresar Numeros");
           tCodigo.requestFocus();
        
        
        }
    }//GEN-LAST:event_tPrecioFocusLost

    private void tDescFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tDescFocusLost
         
        if (tDesc.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "Debe agregar la descripcion");
           tDesc.requestFocus();
        }
    }//GEN-LAST:event_tDescFocusLost

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
       
         llenarTabla();
    }//GEN-LAST:event_cbCategoriaActionPerformed

    private void tProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tProductosMouseClicked
         
        bActualizar.setEnabled(true);
        bEliminar.setEnabled(true);
        
        int filaSelec = tProductos.getSelectedRow();
        int codigo = (Integer) tProductos.getValueAt(filaSelec, 0);
        String desc = (String)tProductos.getValueAt(filaSelec, 1);
        Double precio = (Double)tProductos.getValueAt(filaSelec, 2);
        String rubro = (String)tProductos.getValueAt(filaSelec, 3);
        int stock = (Integer)tProductos.getValueAt(filaSelec, 4);
        tCodigo.setText(codigo+"");
        tDesc.setText(desc);
        tPrecio.setText(precio+"");
        cbRubro.setSelectedItem(rubro);
        sStock.setValue(stock);
        activarCampos();
        
    }//GEN-LAST:event_tProductosMouseClicked

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        int cod = Integer.parseInt(tCodigo.getText());
        String desc = tDesc.getText();
        double precio = Double.parseDouble(tPrecio.getText());
        String rubro = (String) cbRubro.getSelectedItem();
        int stock =(Integer)sStock.getValue();
        Producto prod = new Producto(cod,desc,precio,rubro,stock);
        pd.eliminarProd(prod);
        limpiar();
        desactivarCampos();
        llenarTabla();
        bEliminar.setEnabled(false);
        
    }//GEN-LAST:event_bEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bBuevo;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbRubro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner sStock;
    private javax.swing.JTextField tCodigo;
    private javax.swing.JTextField tDesc;
    private javax.swing.JTextField tPrecio;
    private javax.swing.JTable tProductos;
    // End of variables declaration//GEN-END:variables
}
